#149 Update Constitution links and pdf
CSSUoB/cssuob.github.io pull request #166
Opened 2021-09-04 08:38 UTC by sapphyree

Update CSS Constitution file and clean up links on about as well as adding a /constitution redirect so it can be directly used instead of using /constitution.pdf. Closes #149.

2021-09-04 18:21 UTC, AlexJBanks requested changes
Given that there's only one link to our Constitution now, can the Constitution section of `/about` section be reworded to 
> That means we've got a constitution that you can **_read here_**. We recommend that all our members read it at least once.

2021-09-05 08:08 UTC, sapphyree commented
> Given that there's only one link to our Constitution now, can the Constitution section of `/about` section be reworded to 
> > That means we've got a constitution that you can **_read here_**. We recommend that all our members read it at least once. 

I'm not entirely sure I agree with this. Part of me prefers the fact that it's sectioned off and very clearly visible. It being a hyperlink in a sentence feels to me like it'll be ignored by those reading over the about section.

I can do this if you're absolutely sure, though. Perhaps there's another solution as well?

2021-09-05 12:09 UTC, LikkanChung commented
> > Given that there's only one link to our Constitution now, can the Constitution section of `/about` section be reworded to 
> > > That means we've got a constitution that you can **_read here_**. We recommend that all our members read it at least once. 
> 
> I'm not entirely sure I agree with this. Part of me prefers the fact that it's sectioned off and very clearly visible. It being a hyperlink in a sentence feels to me like it'll be ignored by those reading over the about section.
> 
> I can do this if you're absolutely sure, though. Perhaps there's another solution as well? 

I don't think it matters either way

2021-09-05 12:09 UTC, LikkanChung approved these changes

2021-09-05 12:39 UTC, Danyc0 commented
i agree with @sapphyree, it's nice that it's made obvious and clearly visible by being in its own section

2021-09-05 12:44 UTC, AlexJBanks commented
Can we find a suitable compromise then, at the moment I'm not that happy with it just being a link on a single bullet point doing looking a bit sad on its own.

![Screenshot_20210905-134229.png](https://user-images.githubusercontent.com/13523129/132127224-ee49102f-75f3-4cff-aa01-d1f5562856b7.png)

Could we turn the Constitution and Agendas links into buttons?

2021-09-06 13:21 UTC, Jack-Development commented
We coud potenitally change the text to read like "Here is our constitution and agendas for you to read" and reuse the styles of the buttons higher up?

2021-09-06 14:05 UTC, AlexJBanks commented on about.html
> +        <div class="flex-container flex-v-center">
these div are probably redundant but can be tidyied up in #153

2021-09-06 14:06 UTC, AlexJBanks approved these changes

2021-09-06 14:09 UTC, merged