Add Sponsorship Logos
CSSUoB/cssuob.github.io pull request #194
Opened 2021-11-09 20:42 UTC by El-Mathematica

2021-11-09 20:46 UTC, JTWWilson requested changes

2021-11-09 20:46 UTC, JTWWilson commented on index.html
> +        <img src="cssuob.github.io\assets\images\logos\university_of_birmingham_logo.png" alt="University of Birmingham Logo">
Not pointing properly to the images, change to just /assets/images/logos/{NAME}

2021-11-09 20:46 UTC, JTWWilson commented on index.html
> +<span class="delay d13">    <i c=comment itemscope itemtype=http://schema.org/Organization><span aria-hidden=true>/*</span>         <h1 itemprop= name>Computer Science Society</h1>         <span aria
unnecessary

2021-11-09 21:06 UTC, AlexJBanks commented
![Screenshot_20211109-210545](https://user-images.githubusercontent.com/13523129/141004605-4d0d414d-5fe8-4337-a7c0-20285ea70280.png)
On mobile, first image renders too low on the screen. Rest are not on screen

2022-05-03 18:09 UTC, AlexJBanks commented
superseded by #218

2022-05-03 18:09 UTC, closed without merging