Add new committee to committee page
CSSUoB/cssuob.github.io pull request #562
Opened 2024-03-08 19:31 UTC by qPalee

Need to add me and Leaf to committee page for 2023-24

2024-03-08 19:33 UTC, codemicro requested changes

2024-03-08 19:33 UTC, codemicro commented on _data/committee/2023-24.yaml
> +Ôacademic_year: 2023/2024 #postfix: Elect
!!! funky character alert !!!

2024-03-08 19:36 UTC, codemicro requested changes

2024-03-08 19:36 UTC, codemicro commented on _site/_redirects
Also didn't spot this again but also you probably didn't mean to delete all the redirects

2024-03-08 19:37 UTC, qPalee commented on _site/_redirects
how have i done that

2024-03-08 19:38 UTC, codemicro commented on _site/_redirects
absolute skillz

2024-03-09 19:45 UTC, codemicro requested changes

2024-03-09 19:45 UTC, codemicro commented on _data/committee/2023-24.yaml
> +
This block is indented one level too far and has ceased to be valid YAML

2024-03-11 20:30 UTC, codemicro requested changes

2024-03-11 20:30 UTC, codemicro commented on _data/committee/2023-24.yaml
> +    picture: /assets/committee/2023-24/mini/lee.png
Your image is a `.jpg`, not a `.png`

2024-03-13 14:16 UTC, codemicro approved these changes
👍😀👍

Not going to wait for @antikitten but he can open a new PR if he'd like

2024-03-13 14:17 UTC, merged